// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0AQSyTPiwnFw5rdl-Oy2yXgPpiAC1NVc',
    appId: '1:576904705793:web:96b5e28faba52b9c47cd00',
    messagingSenderId: '576904705793',
    projectId: 'fixmate-fb750',
    authDomain: 'fixmate-fb750.firebaseapp.com',
    storageBucket: 'fixmate-fb750.firebasestorage.app',
    measurementId: 'G-CYY7SE0ZCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpPaslMvg24F8Fq3ePRwPlP1ayS7Ryfcw',
    appId: '1:576904705793:android:cd183fc9b6dd28a047cd00',
    messagingSenderId: '576904705793',
    projectId: 'fixmate-fb750',
    storageBucket: 'fixmate-fb750.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9rKFaVAQ4JV3zMDinCEUTv3HQm_wqGNY',
    appId: '1:576904705793:ios:5f3909a067b67b2d47cd00',
    messagingSenderId: '576904705793',
    projectId: 'fixmate-fb750',
    storageBucket: 'fixmate-fb750.firebasestorage.app',
    iosBundleId: 'com.example.fixMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9rKFaVAQ4JV3zMDinCEUTv3HQm_wqGNY',
    appId: '1:576904705793:ios:5f3909a067b67b2d47cd00',
    messagingSenderId: '576904705793',
    projectId: 'fixmate-fb750',
    storageBucket: 'fixmate-fb750.firebasestorage.app',
    iosBundleId: 'com.example.fixMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0AQSyTPiwnFw5rdl-Oy2yXgPpiAC1NVc',
    appId: '1:576904705793:web:7ca82a6c6cedc31447cd00',
    messagingSenderId: '576904705793',
    projectId: 'fixmate-fb750',
    authDomain: 'fixmate-fb750.firebaseapp.com',
    storageBucket: 'fixmate-fb750.firebasestorage.app',
    measurementId: 'G-YLVESR0QLN',
  );
}
